### ISSUE TITLE
Final confirmation of uploading to webplate

### ISSUE THREAD

**Issue by TakWolf** [aseprite-quest/aseprite-language-chinese-simplified#1]
Hi @dacap, I plan to upload a Simplified Chinese translation, But just in case, I need to conduct a final confirmation.

The current translation is completely retranslated by me. In principle, this does not have any attribution issues.

Prior to this, [J-11/Aseprite-Simplified-Chinese](https://github.com/J-11/Aseprite-Simplified-Chinese) is the mainstream version in the community. And I cannot completely deny that I did not refer to this translation. I used to be a user of this language pack as well. (Even considering this, I still believe that there is no issue of attribution).
Therefore, I think his contribution should be signed: https://github.com/aseprite-quest/aseprite-language-chinese-simplified/blob/master/data/zh-hans.ini#L2

So, how should I do it

**Comment by TakWolf** [comment]
Latest progress:

There has established a new translation proofreading team on the basis of this translation, the contribution has started to be submitted (Decentralized use of their own accounts, participants will retain their contributions).

The remaining issue is:
I personally believe that his contribution should be retained [J-11/Aseprite-Simplified-Chinese](https://github.com/J-11/Aseprite-Simplified-Chinese)

**Comment by dacap** [comment]
Hi @TakWolf! If J-11 is part of the translation (or your work is based their work), we should contact them to know if they want to be part of the Weblate project (including their work licensed under CC-BY-4.0).

If you think that your translation is an original work, you can upload it directly.
